# What is the name of the lobby world
Lobby: "world"

#---------------BETA--------------#

#World Settings:
MinY: 20 # Dont change if you dont want to have Unwanted results!
DisX: 125 # Distance Between Islands on X Coordinate
DisZ: 125 # Distance between Islands on Z Coordinate
SkyWorldName: Skyblock #The name that will load and generate the map in

#---------------BETA--------------#

#WIP=============================WIP#
Language: eng
islandPerWorld: 100
DefaultWorldName: Skyland

EnableAntiTrollSystem: true
PVPenableonislands: false

#World Settings:
MinY: 20 # Dont change if you dont want to have Unwanted results!
DisX: 125 # Distance Between Islands on X Coordinate
DisZ: 125 # Distance between Islands on Z Coordinate

#WIP=============================WIP#
