#---------------BETA--------------#

# What is the name of the lobby world
Lobby: "world"

#World Settings:
#Dont change Y if you dont want to have Unwanted results!
MinY: 20
# Distance Between Islands on X Coordinate
DisX: 125 
# Distance between Islands on Z Coordinate
DisZ: 125 
#The name that will load and generate the map in
SkyWorldName: Skyblock 

#Plugin Settings:
Language: eng
EnableAntiTrollSystem: true
PVPEnableOnIslands: false
#WIP
IslandPerWorld: 100

